// Generated by gencpp from file drl_project/DeleteGazeboModelsWithTarget.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELSWITHTARGET_H
#define DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELSWITHTARGET_H

#include <ros/service_traits.h>


#include <drl_project/DeleteGazeboModelsWithTargetRequest.h>
#include <drl_project/DeleteGazeboModelsWithTargetResponse.h>


namespace drl_project
{

struct DeleteGazeboModelsWithTarget
{

typedef DeleteGazeboModelsWithTargetRequest Request;
typedef DeleteGazeboModelsWithTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteGazeboModelsWithTarget
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::DeleteGazeboModelsWithTarget > {
  static const char* value()
  {
    return "b129c2666f54b5803dca2de530a0d745";
  }

  static const char* value(const ::drl_project::DeleteGazeboModelsWithTarget&) { return value(); }
};

template<>
struct DataType< ::drl_project::DeleteGazeboModelsWithTarget > {
  static const char* value()
  {
    return "drl_project/DeleteGazeboModelsWithTarget";
  }

  static const char* value(const ::drl_project::DeleteGazeboModelsWithTarget&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsWithTargetRequest> should match 
// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsWithTarget > 
template<>
struct MD5Sum< ::drl_project::DeleteGazeboModelsWithTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::DeleteGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::DeleteGazeboModelsWithTargetRequest> should match 
// service_traits::DataType< ::drl_project::DeleteGazeboModelsWithTarget > 
template<>
struct DataType< ::drl_project::DeleteGazeboModelsWithTargetRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::DeleteGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsWithTargetResponse> should match 
// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsWithTarget > 
template<>
struct MD5Sum< ::drl_project::DeleteGazeboModelsWithTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::DeleteGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsWithTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::DeleteGazeboModelsWithTargetResponse> should match 
// service_traits::DataType< ::drl_project::DeleteGazeboModelsWithTarget > 
template<>
struct DataType< ::drl_project::DeleteGazeboModelsWithTargetResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::DeleteGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsWithTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELSWITHTARGET_H
