// Generated by gencpp from file drl_project/DeleteGazeboModels.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELS_H
#define DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELS_H

#include <ros/service_traits.h>


#include <drl_project/DeleteGazeboModelsRequest.h>
#include <drl_project/DeleteGazeboModelsResponse.h>


namespace drl_project
{

struct DeleteGazeboModels
{

typedef DeleteGazeboModelsRequest Request;
typedef DeleteGazeboModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteGazeboModels
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::DeleteGazeboModels > {
  static const char* value()
  {
    return "b129c2666f54b5803dca2de530a0d745";
  }

  static const char* value(const ::drl_project::DeleteGazeboModels&) { return value(); }
};

template<>
struct DataType< ::drl_project::DeleteGazeboModels > {
  static const char* value()
  {
    return "drl_project/DeleteGazeboModels";
  }

  static const char* value(const ::drl_project::DeleteGazeboModels&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsRequest> should match 
// service_traits::MD5Sum< ::drl_project::DeleteGazeboModels > 
template<>
struct MD5Sum< ::drl_project::DeleteGazeboModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::DeleteGazeboModels >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::DeleteGazeboModelsRequest> should match 
// service_traits::DataType< ::drl_project::DeleteGazeboModels > 
template<>
struct DataType< ::drl_project::DeleteGazeboModelsRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::DeleteGazeboModels >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::DeleteGazeboModelsResponse> should match 
// service_traits::MD5Sum< ::drl_project::DeleteGazeboModels > 
template<>
struct MD5Sum< ::drl_project::DeleteGazeboModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::DeleteGazeboModels >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::DeleteGazeboModelsResponse> should match 
// service_traits::DataType< ::drl_project::DeleteGazeboModels > 
template<>
struct DataType< ::drl_project::DeleteGazeboModelsResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::DeleteGazeboModels >::value();
  }
  static const char* value(const ::drl_project::DeleteGazeboModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_DELETEGAZEBOMODELS_H
