// Generated by gencpp from file drl_project/LoadGazeboModelsWithTarget.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSWITHTARGET_H
#define DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSWITHTARGET_H

#include <ros/service_traits.h>


#include <drl_project/LoadGazeboModelsWithTargetRequest.h>
#include <drl_project/LoadGazeboModelsWithTargetResponse.h>


namespace drl_project
{

struct LoadGazeboModelsWithTarget
{

typedef LoadGazeboModelsWithTargetRequest Request;
typedef LoadGazeboModelsWithTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadGazeboModelsWithTarget
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::LoadGazeboModelsWithTarget > {
  static const char* value()
  {
    return "5f08058997a8852ae0a653fa727e7b80";
  }

  static const char* value(const ::drl_project::LoadGazeboModelsWithTarget&) { return value(); }
};

template<>
struct DataType< ::drl_project::LoadGazeboModelsWithTarget > {
  static const char* value()
  {
    return "drl_project/LoadGazeboModelsWithTarget";
  }

  static const char* value(const ::drl_project::LoadGazeboModelsWithTarget&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsWithTargetRequest> should match 
// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsWithTarget > 
template<>
struct MD5Sum< ::drl_project::LoadGazeboModelsWithTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::LoadGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::LoadGazeboModelsWithTargetRequest> should match 
// service_traits::DataType< ::drl_project::LoadGazeboModelsWithTarget > 
template<>
struct DataType< ::drl_project::LoadGazeboModelsWithTargetRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::LoadGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsWithTargetResponse> should match 
// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsWithTarget > 
template<>
struct MD5Sum< ::drl_project::LoadGazeboModelsWithTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::LoadGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsWithTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::LoadGazeboModelsWithTargetResponse> should match 
// service_traits::DataType< ::drl_project::LoadGazeboModelsWithTarget > 
template<>
struct DataType< ::drl_project::LoadGazeboModelsWithTargetResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::LoadGazeboModelsWithTarget >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsWithTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSWITHTARGET_H
