// Generated by gencpp from file drl_project/LoadGazeboModels.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_LOADGAZEBOMODELS_H
#define DRL_PROJECT_MESSAGE_LOADGAZEBOMODELS_H

#include <ros/service_traits.h>


#include <drl_project/LoadGazeboModelsRequest.h>
#include <drl_project/LoadGazeboModelsResponse.h>


namespace drl_project
{

struct LoadGazeboModels
{

typedef LoadGazeboModelsRequest Request;
typedef LoadGazeboModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadGazeboModels
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::LoadGazeboModels > {
  static const char* value()
  {
    return "5f08058997a8852ae0a653fa727e7b80";
  }

  static const char* value(const ::drl_project::LoadGazeboModels&) { return value(); }
};

template<>
struct DataType< ::drl_project::LoadGazeboModels > {
  static const char* value()
  {
    return "drl_project/LoadGazeboModels";
  }

  static const char* value(const ::drl_project::LoadGazeboModels&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsRequest> should match 
// service_traits::MD5Sum< ::drl_project::LoadGazeboModels > 
template<>
struct MD5Sum< ::drl_project::LoadGazeboModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::LoadGazeboModels >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::LoadGazeboModelsRequest> should match 
// service_traits::DataType< ::drl_project::LoadGazeboModels > 
template<>
struct DataType< ::drl_project::LoadGazeboModelsRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::LoadGazeboModels >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::LoadGazeboModelsResponse> should match 
// service_traits::MD5Sum< ::drl_project::LoadGazeboModels > 
template<>
struct MD5Sum< ::drl_project::LoadGazeboModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::LoadGazeboModels >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::LoadGazeboModelsResponse> should match 
// service_traits::DataType< ::drl_project::LoadGazeboModels > 
template<>
struct DataType< ::drl_project::LoadGazeboModelsResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::LoadGazeboModels >::value();
  }
  static const char* value(const ::drl_project::LoadGazeboModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_LOADGAZEBOMODELS_H
