// Generated by gencpp from file drl_project/LoadGazeboModelsRequest.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSREQUEST_H
#define DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drl_project
{
template <class ContainerAllocator>
struct LoadGazeboModelsRequest_
{
  typedef LoadGazeboModelsRequest_<ContainerAllocator> Type;

  LoadGazeboModelsRequest_()
    : table_pose()
    , table_reference_frame()
    , block_pose()
    , block_reference_frame()  {
    }
  LoadGazeboModelsRequest_(const ContainerAllocator& _alloc)
    : table_pose(_alloc)
    , table_reference_frame(_alloc)
    , block_pose(_alloc)
    , block_reference_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _table_pose_type;
  _table_pose_type table_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _table_reference_frame_type;
  _table_reference_frame_type table_reference_frame;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _block_pose_type;
  _block_pose_type block_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _block_reference_frame_type;
  _block_reference_frame_type block_reference_frame;





  typedef boost::shared_ptr< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadGazeboModelsRequest_

typedef ::drl_project::LoadGazeboModelsRequest_<std::allocator<void> > LoadGazeboModelsRequest;

typedef boost::shared_ptr< ::drl_project::LoadGazeboModelsRequest > LoadGazeboModelsRequestPtr;
typedef boost::shared_ptr< ::drl_project::LoadGazeboModelsRequest const> LoadGazeboModelsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drl_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/dewe/ros_ws/src/baxter_common/baxter_core_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/kinetic/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f08058997a8852ae0a653fa727e7b80";
  }

  static const char* value(const ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f08058997a8852aULL;
  static const uint64_t static_value2 = 0xe0a653fa727e7b80ULL;
};

template<class ContainerAllocator>
struct DataType< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drl_project/LoadGazeboModelsRequest";
  }

  static const char* value(const ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] table_pose\n\
string table_reference_frame\n\
float64[] block_pose\n\
string block_reference_frame\n\
";
  }

  static const char* value(const ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table_pose);
      stream.next(m.table_reference_frame);
      stream.next(m.block_pose);
      stream.next(m.block_reference_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadGazeboModelsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drl_project::LoadGazeboModelsRequest_<ContainerAllocator>& v)
  {
    s << indent << "table_pose[]" << std::endl;
    for (size_t i = 0; i < v.table_pose.size(); ++i)
    {
      s << indent << "  table_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.table_pose[i]);
    }
    s << indent << "table_reference_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.table_reference_frame);
    s << indent << "block_pose[]" << std::endl;
    for (size_t i = 0; i < v.block_pose.size(); ++i)
    {
      s << indent << "  block_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.block_pose[i]);
    }
    s << indent << "block_reference_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.block_reference_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_LOADGAZEBOMODELSREQUEST_H
