// Generated by gencpp from file drl_project/Reset.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_RESET_H
#define DRL_PROJECT_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <drl_project/ResetRequest.h>
#include <drl_project/ResetResponse.h>


namespace drl_project
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::Reset > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::drl_project::Reset&) { return value(); }
};

template<>
struct DataType< ::drl_project::Reset > {
  static const char* value()
  {
    return "drl_project/Reset";
  }

  static const char* value(const ::drl_project::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::ResetRequest> should match 
// service_traits::MD5Sum< ::drl_project::Reset > 
template<>
struct MD5Sum< ::drl_project::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::Reset >::value();
  }
  static const char* value(const ::drl_project::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::ResetRequest> should match 
// service_traits::DataType< ::drl_project::Reset > 
template<>
struct DataType< ::drl_project::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::Reset >::value();
  }
  static const char* value(const ::drl_project::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::ResetResponse> should match 
// service_traits::MD5Sum< ::drl_project::Reset > 
template<>
struct MD5Sum< ::drl_project::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::Reset >::value();
  }
  static const char* value(const ::drl_project::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::ResetResponse> should match 
// service_traits::DataType< ::drl_project::Reset > 
template<>
struct DataType< ::drl_project::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::Reset >::value();
  }
  static const char* value(const ::drl_project::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_RESET_H
