// Generated by gencpp from file drl_project/SetTorque.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_SETTORQUE_H
#define DRL_PROJECT_MESSAGE_SETTORQUE_H

#include <ros/service_traits.h>


#include <drl_project/SetTorqueRequest.h>
#include <drl_project/SetTorqueResponse.h>


namespace drl_project
{

struct SetTorque
{

typedef SetTorqueRequest Request;
typedef SetTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTorque
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::SetTorque > {
  static const char* value()
  {
    return "a50b48b6ae6e4ba807756e2843deb824";
  }

  static const char* value(const ::drl_project::SetTorque&) { return value(); }
};

template<>
struct DataType< ::drl_project::SetTorque > {
  static const char* value()
  {
    return "drl_project/SetTorque";
  }

  static const char* value(const ::drl_project::SetTorque&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::SetTorqueRequest> should match 
// service_traits::MD5Sum< ::drl_project::SetTorque > 
template<>
struct MD5Sum< ::drl_project::SetTorqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SetTorque >::value();
  }
  static const char* value(const ::drl_project::SetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SetTorqueRequest> should match 
// service_traits::DataType< ::drl_project::SetTorque > 
template<>
struct DataType< ::drl_project::SetTorqueRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::SetTorque >::value();
  }
  static const char* value(const ::drl_project::SetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::SetTorqueResponse> should match 
// service_traits::MD5Sum< ::drl_project::SetTorque > 
template<>
struct MD5Sum< ::drl_project::SetTorqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SetTorque >::value();
  }
  static const char* value(const ::drl_project::SetTorqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SetTorqueResponse> should match 
// service_traits::DataType< ::drl_project::SetTorque > 
template<>
struct DataType< ::drl_project::SetTorqueResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::SetTorque >::value();
  }
  static const char* value(const ::drl_project::SetTorqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_SETTORQUE_H
