// Generated by gencpp from file drl_project/SetTorqueRequest.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_SETTORQUEREQUEST_H
#define DRL_PROJECT_MESSAGE_SETTORQUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drl_project
{
template <class ContainerAllocator>
struct SetTorqueRequest_
{
  typedef SetTorqueRequest_<ContainerAllocator> Type;

  SetTorqueRequest_()
    : t_value()
    , g_value(0.0)  {
    }
  SetTorqueRequest_(const ContainerAllocator& _alloc)
    : t_value(_alloc)
    , g_value(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _t_value_type;
  _t_value_type t_value;

   typedef double _g_value_type;
  _g_value_type g_value;





  typedef boost::shared_ptr< ::drl_project::SetTorqueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drl_project::SetTorqueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTorqueRequest_

typedef ::drl_project::SetTorqueRequest_<std::allocator<void> > SetTorqueRequest;

typedef boost::shared_ptr< ::drl_project::SetTorqueRequest > SetTorqueRequestPtr;
typedef boost::shared_ptr< ::drl_project::SetTorqueRequest const> SetTorqueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drl_project::SetTorqueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drl_project::SetTorqueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drl_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/dewe/ros_ws/src/baxter_common/baxter_core_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'control_msgs': ['/opt/ros/kinetic/share/control_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drl_project::SetTorqueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drl_project::SetTorqueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drl_project::SetTorqueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a50b48b6ae6e4ba807756e2843deb824";
  }

  static const char* value(const ::drl_project::SetTorqueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa50b48b6ae6e4ba8ULL;
  static const uint64_t static_value2 = 0x07756e2843deb824ULL;
};

template<class ContainerAllocator>
struct DataType< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drl_project/SetTorqueRequest";
  }

  static const char* value(const ::drl_project::SetTorqueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] t_value\n\
float64 g_value\n\
";
  }

  static const char* value(const ::drl_project::SetTorqueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t_value);
      stream.next(m.g_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTorqueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drl_project::SetTorqueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drl_project::SetTorqueRequest_<ContainerAllocator>& v)
  {
    s << indent << "t_value[]" << std::endl;
    for (size_t i = 0; i < v.t_value.size(); ++i)
    {
      s << indent << "  t_value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.t_value[i]);
    }
    s << indent << "g_value: ";
    Printer<double>::stream(s, indent + "  ", v.g_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_SETTORQUEREQUEST_H
