// Generated by gencpp from file drl_project/SpawnBlocks.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_SPAWNBLOCKS_H
#define DRL_PROJECT_MESSAGE_SPAWNBLOCKS_H

#include <ros/service_traits.h>


#include <drl_project/SpawnBlocksRequest.h>
#include <drl_project/SpawnBlocksResponse.h>


namespace drl_project
{

struct SpawnBlocks
{

typedef SpawnBlocksRequest Request;
typedef SpawnBlocksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnBlocks
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::SpawnBlocks > {
  static const char* value()
  {
    return "3a354f469531ae7418e2e3001fc52e12";
  }

  static const char* value(const ::drl_project::SpawnBlocks&) { return value(); }
};

template<>
struct DataType< ::drl_project::SpawnBlocks > {
  static const char* value()
  {
    return "drl_project/SpawnBlocks";
  }

  static const char* value(const ::drl_project::SpawnBlocks&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::SpawnBlocksRequest> should match 
// service_traits::MD5Sum< ::drl_project::SpawnBlocks > 
template<>
struct MD5Sum< ::drl_project::SpawnBlocksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SpawnBlocks >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SpawnBlocksRequest> should match 
// service_traits::DataType< ::drl_project::SpawnBlocks > 
template<>
struct DataType< ::drl_project::SpawnBlocksRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::SpawnBlocks >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::SpawnBlocksResponse> should match 
// service_traits::MD5Sum< ::drl_project::SpawnBlocks > 
template<>
struct MD5Sum< ::drl_project::SpawnBlocksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SpawnBlocks >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SpawnBlocksResponse> should match 
// service_traits::DataType< ::drl_project::SpawnBlocks > 
template<>
struct DataType< ::drl_project::SpawnBlocksResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::SpawnBlocks >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_SPAWNBLOCKS_H
