// Generated by gencpp from file drl_project/SpawnBlocksWithTarget.msg
// DO NOT EDIT!


#ifndef DRL_PROJECT_MESSAGE_SPAWNBLOCKSWITHTARGET_H
#define DRL_PROJECT_MESSAGE_SPAWNBLOCKSWITHTARGET_H

#include <ros/service_traits.h>


#include <drl_project/SpawnBlocksWithTargetRequest.h>
#include <drl_project/SpawnBlocksWithTargetResponse.h>


namespace drl_project
{

struct SpawnBlocksWithTarget
{

typedef SpawnBlocksWithTargetRequest Request;
typedef SpawnBlocksWithTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnBlocksWithTarget
} // namespace drl_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drl_project::SpawnBlocksWithTarget > {
  static const char* value()
  {
    return "3a354f469531ae7418e2e3001fc52e12";
  }

  static const char* value(const ::drl_project::SpawnBlocksWithTarget&) { return value(); }
};

template<>
struct DataType< ::drl_project::SpawnBlocksWithTarget > {
  static const char* value()
  {
    return "drl_project/SpawnBlocksWithTarget";
  }

  static const char* value(const ::drl_project::SpawnBlocksWithTarget&) { return value(); }
};


// service_traits::MD5Sum< ::drl_project::SpawnBlocksWithTargetRequest> should match 
// service_traits::MD5Sum< ::drl_project::SpawnBlocksWithTarget > 
template<>
struct MD5Sum< ::drl_project::SpawnBlocksWithTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SpawnBlocksWithTarget >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SpawnBlocksWithTargetRequest> should match 
// service_traits::DataType< ::drl_project::SpawnBlocksWithTarget > 
template<>
struct DataType< ::drl_project::SpawnBlocksWithTargetRequest>
{
  static const char* value()
  {
    return DataType< ::drl_project::SpawnBlocksWithTarget >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksWithTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drl_project::SpawnBlocksWithTargetResponse> should match 
// service_traits::MD5Sum< ::drl_project::SpawnBlocksWithTarget > 
template<>
struct MD5Sum< ::drl_project::SpawnBlocksWithTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drl_project::SpawnBlocksWithTarget >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksWithTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drl_project::SpawnBlocksWithTargetResponse> should match 
// service_traits::DataType< ::drl_project::SpawnBlocksWithTarget > 
template<>
struct DataType< ::drl_project::SpawnBlocksWithTargetResponse>
{
  static const char* value()
  {
    return DataType< ::drl_project::SpawnBlocksWithTarget >::value();
  }
  static const char* value(const ::drl_project::SpawnBlocksWithTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRL_PROJECT_MESSAGE_SPAWNBLOCKSWITHTARGET_H
